# Generated by Django 5.0.4 on 2024-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
