# Generated by Django 5.0.4 on 2024-06-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0002_dream_completion_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('minutes_needed_per_week', models.IntegerField()),
                ('minutes_done_per_week', models.IntegerField()),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dreams.dream')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
    ]
